modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/cech12/UsefulHats/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="usefulhats"
    version="${file.jarVersion}"
    displayName="Useful Hats"
    displayURL="https://github.com/cech12/UsefulHats"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds some useful hats.
    '''
[[dependencies.usefulhats]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.usefulhats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.usefulhats]]
    modId="curios"
    mandatory=false
    versionRange="[2.0.2.4,)"
    ordering="NONE"
    side="BOTH"